duck_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../databases/dev.db
      alias: dev
      attach:
        - path: ../databases/raw.db
          alias: raw
        - path: ../databases/production.db
          alias: prod